[build]
  command = "npm ci --omit=dev"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/carrito"
  to = "/carrito.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200